version: 1
validation: sovereign
default_denom: stake
accounts:
  - name: alice
    coins:
      - 20000token
      - 200000000stake
  - name: bob
    coins:
      - 10000token
      - 100000000stake
client:
  openapi:
    path: "docs/static/openapi.json"
faucet:
  name: bob
  coins:
    - 5token
    - 100000stake
  host: 0.0.0.0:4500
genesis:
  chain_id: "mychain-1"
validators:
  - name: alice
    bonded: 100000000stake
  - name: validator1
    bonded: 200000000stake
  - name: validator2
    bonded: 100000000stake
